application:
  port: 8081

debug: true

mongo:
  username: ""
  password: ""
  port: 27017
  host: "10.20.30.20"
  db: "study_pwa"
  collection: "users"
  require_auth: false

redis:
  url: "redis://10.20.30.5:6379"
  pool_max_open: 16
  pool_max_idle: 8
  pool_timeout_seconds: 1
  pool_expire_seconds: 60

email:
  host: "smtp.gmail.com"
  host_user: ""
  host_user_password: ""

doctor:
  name: "the good doctor"
  email: "good_doctor@email.com"
  phone: "(954) 555-6574"
  address: "health dr., FL"
  speciality: "general practitoner"

sqlite:
  db_path: "chores.db"
  schema: "static/schema.sql"
  pragma:
    pool_size: "1"
    connection_timeout: "1"
    foriegn_key: "true"
    journal_mode: "WAL"
    busy_timeout: "5000"
    synchronous: "NORMAL"
    cache_size: "2000"
    temp_store: "memory"
    mmap_size: "4096"
